# Loader

We use the iterators=True in the read_csv() function of pandas to read the csv loop into memory in batches. (If you don’t use the iterators parameter, the csv file with a large amount of data will be read into the memory. The memory is definitely Not enough) The code is as follows:

In [1]:
from Processing.loader import *

In [2]:
data = DataSet(limit=20)

Loading data from data/training/data_3.csv


In [5]:
loader = iter(DataLoader(data, batch_size = 2, shuffle=True))

In [6]:
next(loader)

[('2ezo', '174l'),
 tensor([[20, 12, 21,  ...,  0,  0,  0],
         [20, 17, 21,  ...,  0,  0,  0]]),
 tensor([[[ 28.8650, -36.1100, -15.7820],
          [ 28.2050, -35.2650, -14.7470],
          [ 28.2960, -33.7850, -15.1290],
          ...,
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000]],
 
         [[ 34.1870,  18.8530,  41.6610],
          [ 33.9690,  18.9070,  43.0990],
          [ 32.9410,  17.8620,  43.4660],
          ...,
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000]]], dtype=torch.float64),
 tensor([[144.9332,  59.2721, -39.0411,  ...,   0.0000,   0.0000,   0.0000],
         [164.2882, 170.7135, -33.3104,  ...,   0.0000,   0.0000,   0.0000]],
        dtype=torch.float64),
 tensor([[ -73.2422,  -89.5646,  -65.7283,  ...,    0.0000,    0.0000,
             0.0000],
         [ 181.0000, -146.0499,  -61.8662,  ...,    0.0000

In [28]:
# 
data.data.count()[0]

prot_id    20
y          20
het        20
xyz        20
psi        20
phi        20
omega      20
na         20
nr         20
dtype: int64

In [29]:
data.display()

In [30]:
print("maximum size:", data.max_natoms)

maximum size: 2929


In [31]:
print("minimum size:", data.max_nres)

minimum size: 585


In [32]:
for idx, num in enumerate(loader):
    print(idx)
    print(num[0].shape)
    print(num[1].shape)
    print(num[2].shape)
    print(num[3].shape)
    print(num[4].shape)
    print(num[5].shape)

0
torch.Size([2, 2929])
torch.Size([2, 2929, 3])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 2])
1
torch.Size([2, 2929])
torch.Size([2, 2929, 3])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 2])
2
torch.Size([2, 2929])
torch.Size([2, 2929, 3])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 2])
3
torch.Size([2, 2929])
torch.Size([2, 2929, 3])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 2])
4
torch.Size([2, 2929])
torch.Size([2, 2929, 3])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 2])
5
torch.Size([2, 2929])
torch.Size([2, 2929, 3])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 2])
6
torch.Size([2, 2929])
torch.Size([2, 2929, 3])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 585])
torch.Size([2, 2])
7
torch.Size([2, 2929])
torch.Size([2, 2929, 3])
torch.Size([2, 585])
torch.Size([2