In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
import random

In [7]:
res_list = []
atom_list = []

In [8]:
for i in range(3):
    n_res = random.randint(2, 4)
    np_res = np.random.rand(n_res, 2)
    atom_list_ = []
    for j in range(n_res):
        n_atoms = random.randint(2, 4)
        np_atoms = np.random.rand(n_atoms, 3)
        atom_list_.append(np_atoms)
    atom_list.append(atom_list_)
    res_list.append(np_res)

In [9]:
res_list

[array([[0.73716146, 0.63913424],
        [0.52313399, 0.56958927],
        [0.25740389, 0.7682976 ]]),
 array([[0.08896128, 0.51785106],
        [0.43245243, 0.05529543]]),
 array([[0.0187959 , 0.34609067],
        [0.72824266, 0.35685156],
        [0.60808002, 0.86232583]])]

In [81]:
multicol1 = pd.MultiIndex.from_tuples([('Atoms', 'type'),
                                       ('Atoms', 'x'),
                                       ('Atoms', 'y'),
                                       ('Atoms', 'z')])

In [82]:
data = [[[1, 2, 3, 4],[1, 2, 3, 4]], [[2, 4, 6, 8]]]

In [83]:
for g, group in enumerate(data):
    for r, row in enumerate(group):
        if g+r==0:
            np_data = np.asarray(row)
        else:
            np_data = np.vstack([np_data, row])

In [84]:
np_data

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 4, 6, 8]])

In [209]:
col_names = ['A', 'B', 'C', 'D']
multirows = [(col_names[i], j) for i, d in enumerate(data) for j, _ in enumerate(d)]

In [210]:
multirows

[('A', 0), ('A', 1), ('B', 0)]

In [211]:
multiindx = pd.MultiIndex.from_tuples(multirows)

In [212]:
multiindx

MultiIndex([('A', 0),
            ('A', 1),
            ('B', 0)],
           )

In [213]:
df_multi = pd.DataFrame(np_data,
                        index=multiindx,
                        columns=multicol1)

In [214]:
df_multi

Atoms         
     type  x  y  z
A 0     1  2  3  4
  1     1  2  3  4
B 0     2  4  6  8

In [215]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randint(0,100,size=(2, 4)), columns=list('ABCD'))

In [216]:
df

A   B   C   D
0  47  13  28  63
1   1  71  56  55

In [219]:
for i in range(len(df)):
    A = df.iloc[i]['A']
    df_multi.loc[(col_names[i], 0), column] = A

In [220]:
df_multi

Atoms              D
     type  x  y  z      
A 0     1  2  3  4  47.0
  1     1  2  3  4   NaN
B 0     2  4  6  8   1.0

In [197]:
df_multi.reset_index()

level_0 level_1 Atoms              D
                   type  x  y  z      
0       0       0     1  2  3  4  30.0
1       0       1     1  2  3  4   NaN
2       1       0     2  4  6  8  39.0