In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import random

In [4]:
res_list = []
atom_list = []

In [5]:
for i in range(3):
    n_res = random.randint(2, 4)
    np_res = np.random.rand(n_res, 2)
    atom_list_ = []
    for j in range(n_res):
        n_atoms = random.randint(2, 4)
        np_atoms = np.random.rand(n_atoms, 3)
        atom_list_.append(np_atoms)
    atom_list.append(atom_list_)
    res_list.append(np_res)

In [6]:
res_list

[array([[0.40594889, 0.29020442],
        [0.06151591, 0.73944363]]),
 array([[0.62099707, 0.17510626],
        [0.42973712, 0.28617176]]),
 array([[0.62134076, 0.22324271],
        [0.68113959, 0.94607993],
        [0.24543152, 0.80565981],
        [0.08861951, 0.78863352]])]

In [7]:
multicol1 = pd.MultiIndex.from_tuples([('Atoms', 'type'),
                                       ('Atoms', 'x'),
                                       ('Atoms', 'y'),
                                       ('Atoms', 'z')])

In [8]:
data = [[[1, 2, 3, 4],[1, 2, 3, 4]], [[2, 4, 6, 8]]]

In [9]:
for g, group in enumerate(data):
    for r, row in enumerate(group):
        if g+r==0:
            np_data = np.asarray(row)
        else:
            np_data = np.vstack([np_data, row])

In [10]:
np_data

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 4, 6, 8]])

In [11]:
col_names = ['A', 'B', 'C', 'D']
multirows = [(col_names[i], j) for i, d in enumerate(data) for j, _ in enumerate(d)]

In [12]:
multirows

[('A', 0), ('A', 1), ('B', 0)]

In [13]:
multiindx = pd.MultiIndex.from_tuples(multirows)

In [14]:
multiindx

MultiIndex([('A', 0),
            ('A', 1),
            ('B', 0)],
           )

In [15]:
df_multi = pd.DataFrame(np_data,
                        index=multiindx,
                        columns=multicol1)

In [16]:
df_multi

Atoms         
     type  x  y  z
A 0     1  2  3  4
  1     1  2  3  4
B 0     2  4  6  8

In [17]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randint(0,100,size=(2, 4)), columns=list('ABCD'))

In [18]:
df

A   B   C   D
0  90  57  69  18
1  20  12  76  26